export const INIT_HIKES = "INIT_HIKES";
export const UPDATE_USER = "UPDATE_USER";
export const INIT_COORDS = "INIT_COORDS";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const UPDATE_HIKING_LEVEL = "UPDATE_HIKING_LEVEL";