export const recommendedGear = [
  {
    id: 1,
    difficultyLevel: 'green',
    season: 'winter',
    clothing: 'Wind breaker, long pants, jacket, multiple layers',
    clothingLINK: "#",
    walkingGear: 'None',
    hydrationLevel: 'Water bottle or small hydration pack',
    shoes: 'Running Shoes or Water Proof Shoes',
  },
  {
    id: 2,
    difficultyLevel: 'green',
    season: 'summer',
    clothing: 'Comfortable Clothes, shorts, t-shirt, hat, sunglasses',
    walkingGear: 'None',
    hydrationLevel: 'Water bottle or medium hydration pack',
    shoes: 'Running Shoes or Comfortable Shoes',
  },
  {
    id: 3,
    difficultyLevel: 'greenBlue',
    season: 'winter',
    clothing: 'Wind breaker, long pants, jacket, multiple layers',
    walkingGear: 'None',
    hydrationLevel: 'Water bottle or medium hydration pack',
    shoes: 'Running Shoes or Water Proof Shoes or Hiking Boots',
  },
  {
    id: 4,
    difficultyLevel: 'greenBlue',
    season: 'summer',
    clothing: 'Comfortable Clothes, shorts, t-shirt, hat, sunglasses',
    walkingGear: 'None',
    hydrationLevel: 'Water bottle or medium hydration pack',
    shoes: 'Running Shoes',
  },
  {
    id: 5,
    difficultyLevel: 'blue',
    season: 'winter',
    clothing: 'Wind breaker, long pants, heavy jacket, multiple layers, beanie, gloves',
    walkingGear: 'None',
    hydrationLevel: 'Large Water bottle or Full hydration pack',
    shoes: 'Running Shoes or Water Proof Shoes or Hiking Boots',
  },
  {
    id: 6,
    difficultyLevel: 'blue',
    season: 'summer',
    clothing: 'Comfortable Clothes, shorts, t-shirt, large brimmed hat, sunglasses, sun screen',
    walkingGear: 'None',
    hydrationLevel: 'Water bottle or full hydration pack',
    shoes: 'Running Shoes',
  },
  {
    id: 7,
    difficultyLevel: 'blueBlack',
    season: 'winter',
    clothing: 'Wind breaker, Quick-Drying long pants, heavy jacket, multiple layers, beanie, gloves',
    walkingGear: 'Walking Sticks',
    hydrationLevel: 'Large Water bottle or Full hydration pack',
    shoes: 'Hiking Boots',
  },
  {
    id: 8,
    difficultyLevel: 'blueBlack',
    season: 'summer',
    clothing: 'Comfortable Clothes, shorts or long pants, t-shirt or long sleeved shirt, large brimmed hat, sunglasses, sun screen',
    walkingGear: 'Walking Sticks',
    hydrationLevel: 'Large Water bottle or full hydration pack',
    shoes: 'Running Shoes',
  },
  {
    id: 9,
    difficultyLevel: 'black',
    season: 'winter',
    clothing: 'Wind breaker, Quick-Drying long pants, fleeced heavy jacket, multiple layers, beanie, gloves, warm socks',
    walkingGear: 'Walking Sticks',
    hydrationLevel: 'Large Water bottle, Full hydration pack, or water filter',
    shoes: 'Hiking Boots and/or Gaiters',
  },
  {
    id: 10,
    difficultyLevel: 'black',
    season: 'summer',
    clothing: 'Comfortable Clothes, shorts or long pants, t-shirt or long sleeved shirt, large brimmed hat, sunglasses, sun screen',
    walkingGear: 'Walking Sticks',
    hydrationLevel: 'Large Water bottle or full hydration pack',
    shoes: 'Running Shoes',
  },
  {
    id: 11,
    difficultyLevel: 'blackBlack',
    season: 'winter',
    clothing: 'Wind breaker, Quick-Drying long pants, fleeced heavy jacket, multiple layers, beanie, gloves, warm socks',
    walkingGear: 'Walking Sticks',
    hydrationLevel: 'Large Water bottle, Full hydration pack, or water filter',
    shoes: 'Hiking Boots and/or Gaiters',
  },
  {
    id: 12,
    difficultyLevel: 'blackBlack',
    season: 'summer',
    clothing: 'Comfortable Clothes, shorts or long pants, t-shirt or long sleeved shirt, large brimmed hat, sunglasses, sun screen',
    walkingGear: 'Walking Sticks',
    hydrationLevel: 'Large Water bottle or full hydration pack',
    shoes: 'Running Shoes',
  }
]
