export const recommendedGear = [
  {
    id: 1,
    difficultyLevel: 'green',
    season: 'winter',
    clothing: 'Wind breaker, long pants, jacket, multiple layers',
    clothingLINK: "#",
    walkingGear: 'None',
    hydrationLevel: 'Water bottle or small hydration pack',
    shoes: 'Running Shoes or Water Proof Shoes',
    clothingReason: 'These clothing items are recommended because it is winter and the outdoors have a tendency to be chilly. This hike is not intense at all and will not require more than what you would have put on for going out of the house. ',
    walkingGearReason: 'There is no walking gear recommended because this hike should not be too steep or too long. This trail should be easy enough to enjoy at any pace!',
    hydrationLevelReason: 'The hydration level is based on how relaxed this hike is. Drinking water is very important when being physical and moving around. Make sure you drink enough to not feel thirsty! ',
    shoesReason: 'Running Shoes or Water Proof Shoes are recommended based on the relaxed nature of the trail. The terrain should not be too difficult, but watch out for puddles or snow if it is snowy or raining during the winter. '
  },
  {
    id: 2,
    difficultyLevel: 'green',
    season: 'summer',
    clothing: 'Comfortable Clothes, shorts, t-shirt, hat, sunglasses',
    walkingGear: 'None',
    hydrationLevel: 'Water bottle or medium hydration pack',
    shoes: 'Running Shoes or Comfortable Shoes',
    clothingReason: '',
    walkingGearReason: '',
    hydrationLevelReason: '',
    shoesReason: ''
  },
  {
    id: 3,
    difficultyLevel: 'greenBlue',
    season: 'winter',
    clothing: 'Wind breaker, long pants, jacket, multiple layers',
    walkingGear: 'None',
    hydrationLevel: 'Water bottle or medium hydration pack',
    shoes: 'Running Shoes or Water Proof Shoes or Hiking Boots',
    clothingReason: '',
    walkingGearReason: '',
    hydrationLevelReason: '',
    shoesReason: ''
  },
  {
    id: 4,
    difficultyLevel: 'greenBlue',
    season: 'summer',
    clothing: 'Comfortable Clothes, shorts, t-shirt, hat, sunglasses',
    walkingGear: 'None',
    hydrationLevel: 'Water bottle or medium hydration pack',
    shoes: 'Running Shoes',
    clothingReason: '',
    walkingGearReason: '',
    hydrationLevelReason: '',
    shoesReason: ''
  },
  {
    id: 5,
    difficultyLevel: 'blue',
    season: 'winter',
    clothing: 'Wind breaker, long pants, heavy jacket, multiple layers, beanie, gloves',
    walkingGear: 'None',
    hydrationLevel: 'Large Water bottle or Full hydration pack',
    shoes: 'Running Shoes or Water Proof Shoes or Hiking Boots',
    clothingReason: '',
    walkingGearReason: '',
    hydrationLevelReason: '',
    shoesReason: ''
  },
  {
    id: 6,
    difficultyLevel: 'blue',
    season: 'summer',
    clothing: 'Comfortable Clothes, shorts, t-shirt, large brimmed hat, sunglasses, sun screen',
    walkingGear: 'None',
    hydrationLevel: 'Water bottle or full hydration pack',
    shoes: 'Running Shoes',
    clothingReason: '',
    walkingGearReason: '',
    hydrationLevelReason: '',
    shoesReason: ''
  },
  {
    id: 7,
    difficultyLevel: 'blueBlack',
    season: 'winter',
    clothing: 'Wind breaker, Quick-Drying long pants, heavy jacket, multiple layers, beanie, gloves',
    walkingGear: 'Walking Sticks',
    hydrationLevel: 'Large Water bottle or Full hydration pack',
    shoes: 'Hiking Boots',
    clothingReason: '',
    walkingGearReason: '',
    hydrationLevelReason: '',
    shoesReason: ''
  },
  {
    id: 8,
    difficultyLevel: 'blueBlack',
    season: 'summer',
    clothing: 'Comfortable Clothes, shorts or long pants, t-shirt or long sleeved shirt, large brimmed hat, sunglasses, sun screen',
    walkingGear: 'Walking Sticks',
    hydrationLevel: 'Large Water bottle or full hydration pack',
    shoes: 'Running Shoes',
    clothingReason: '',
    walkingGearReason: '',
    hydrationLevelReason: '',
    shoesReason: ''
  },
  {
    id: 9,
    difficultyLevel: 'black',
    season: 'winter',
    clothing: 'Wind breaker, Quick-Drying long pants, fleeced heavy jacket, multiple layers, beanie, gloves, warm socks',
    walkingGear: 'Walking Sticks',
    hydrationLevel: 'Large Water bottle, Full hydration pack, or water filter',
    shoes: 'Hiking Boots and/or Gaiters',
    clothingReason: '',
    walkingGearReason: '',
    hydrationLevelReason: '',
    shoesReason: ''
  },
  {
    id: 10,
    difficultyLevel: 'black',
    season: 'summer',
    clothing: 'Comfortable Clothes, shorts or long pants, t-shirt or long sleeved shirt, large brimmed hat, sunglasses, sun screen',
    walkingGear: 'Walking Sticks',
    hydrationLevel: 'Large Water bottle or full hydration pack',
    shoes: 'Running Shoes',
    clothingReason: '',
    walkingGearReason: '',
    hydrationLevelReason: '',
    shoesReason: ''
  },
  {
    id: 11,
    difficultyLevel: 'blackBlack',
    season: 'winter',
    clothing: 'Wind breaker, Quick-Drying long pants, fleeced heavy jacket, multiple layers, beanie, gloves, warm socks',
    walkingGear: 'Walking Sticks',
    hydrationLevel: 'Large Water bottle, Full hydration pack, or water filter',
    shoes: 'Hiking Boots and/or Gaiters',
    clothingReason: '',
    walkingGearReason: '',
    hydrationLevelReason: '',
    shoesReason: ''
  },
  {
    id: 12,
    difficultyLevel: 'blackBlack',
    season: 'summer',
    clothing: 'Comfortable Clothes, shorts or long pants, t-shirt or long sleeved shirt, large brimmed hat, sunglasses, sun screen',
    walkingGear: 'Walking Sticks',
    hydrationLevel: 'Large Water bottle or full hydration pack',
    shoes: 'Running Shoes',
    clothingReason: '',
    walkingGearReason: '',
    hydrationLevelReason: '',
    shoesReason: ''
  }
]
